### PR TITLE
Use Poetry for dependency management

### PR DESCRIPTION
**Pull request by george-zubrienko**
Part of #413 

## Scope

- Removed manual publish scripts and pipfile
- Removed `setup.py`
- Added poetry-style toml file and dependency lockfile to ensure contributors can start up with `poetry install`
- Updated all pipelines to use Poetry

### CODE REVIEW

**Review by lidatong — DISMISSED** [review]
Awesome! Thanks for doing this. Does pyproject.toml replacing all the existing build file formats (pipenv, conda, poetry, requirements.txt) stay compatible for users?

**Comment by george-zubrienko** [comment]
> Awesome! Thanks for doing this. Does pyproject.toml replacing all the existing build file formats (pipenv, conda, poetry, requirements.txt) stay compatible for users?

Should be, according to https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#declaring-project-metadata :) 

Requirements can be exported into requirements.txt for pip install with https://python-poetry.org/docs/cli/#export

**Comment by george-zubrienko** [comment]
Forgot to add commit tagging workflow - will do that, update contributor section in README and then merge.
So release process will include one more step - pre-release part, to create tagged commit and a gh release accordingly.

**Comment by george-zubrienko** [comment]
@lidatong sorry for the delay, please have a look at this [commit](https://github.com/lidatong/dataclasses-json/pull/431/commits/d7d11fbe1d07c6e0436bc88acc8ff24fba861926)

It adds a workflow to create github release/tagged commit, so we can create releases regularly. Finally, I've modified the `pythonpackage.yaml` to replace version numbers from git tag so we release correct version from that flow :)

**Comment by lidatong** [comment]
> @lidatong sorry for the delay, please have a look at this [commit](https://github.com/lidatong/dataclasses-json/pull/431/commits/d7d11fbe1d07c6e0436bc88acc8ff24fba861926)
> 
> It adds a workflow to create github release/tagged commit, so we can create releases regularly. Finally, I've modified the `pythonpackage.yaml` to replace version numbers from git tag so we release correct version from that flow :)

looks good thanks for making the automation better with the semver tagging! would this still work with trusted publishing? i saw the workflow is now directly running `poetry publish` instead of using the pypa gh action

**Comment by george-zubrienko** [comment]
> > @lidatong sorry for the delay, please have a look at this [commit](https://github.com/lidatong/dataclasses-json/pull/431/commits/d7d11fbe1d07c6e0436bc88acc8ff24fba861926)
> > It adds a workflow to create github release/tagged commit, so we can create releases regularly. Finally, I've modified the `pythonpackage.yaml` to replace version numbers from git tag so we release correct version from that flow :)
> 
> looks good thanks for making the automation better with the semver tagging! would this still work with trusted publishing? i saw the workflow is now directly running `poetry publish` instead of using the pypa gh action

Yeah it should work, poetry publish is basically the same as pypa gh action - but if you want we can test on one of our OSS repos first

**Comment by george-zubrienko** [comment]
Actually, we can also just do the `poetry publish` and publish with pypa - I think that would work 200% - will update tomorrow

**Comment by george-zubrienko** [comment]
@lidatong updated, just to make sure, this is the result of `poetry build`:

```
> ~/PycharmProjects/dataclasses-json$ poetry build
Building dataclasses-json (0.0.0)
  - Building sdist
  - Built dataclasses_json-0.0.0.tar.gz
  - Building wheel
  - Built dataclasses_json-0.0.0-py3-none-any.whl
> ~/PycharmProjects/dataclasses-json$ ls
LICENSE  README.md  dataclasses_json  dist  poetry.lock  pyproject.toml  tests  venv
> ~/PycharmProjects/dataclasses-json$ ls dist/
dataclasses_json-0.0.0-py3-none-any.whl  dataclasses_json-0.0.0.tar.gz
```

**Review by lidatong — APPROVED** [review]
> @lidatong updated, just to make sure, this is the result of `poetry build`:
> 
> ```
> > ~/PycharmProjects/dataclasses-json$ poetry build
> Building dataclasses-json (0.0.0)
>   - Building sdist
>   - Built dataclasses_json-0.0.0.tar.gz
>   - Building wheel
>   - Built dataclasses_json-0.0.0-py3-none-any.whl
> > ~/PycharmProjects/dataclasses-json$ ls
> LICENSE  README.md  dataclasses_json  dist  poetry.lock  pyproject.toml  tests  venv
> > ~/PycharmProjects/dataclasses-json$ ls dist/
> dataclasses_json-0.0.0-py3-none-any.whl  dataclasses_json-0.0.0.tar.gz
> ```

ok great, this looks good! we can keep trusted publishing this way. thanks again for the nice CI improvements :D

**Pull request merged**
