### PR TITLE
feat: Implement dymamic versioning

### LINKED ISSUE #446: [FEATURE] Implement dynamic versioning for releases
### Description

Since the move to `poetry` (thanks for moving to a proper PEP517 build system), it seems the way versions are handled are through this GitHub Actions script:

https://github.com/lidatong/dataclasses-json/blob/v0.5.13/.github/workflows/pythonpackage.yml#L72-L73

This might work fine for people using releases directly from GitHub, but for everyone else ([including Debian, where I maintain the `dataclasses-json` package](https://tracker.debian.org/pkg/dataclasses-json)), this means the version has to be patched at build in hacky way.

I understand the convenience of using git tags to manage versioning, but a "proper" dynamic versioning system would make things much easier for distros packaging this library :) The "classic" example of dynamic versioning based on git tags is `setuptools-scm`, which has a well-supported flow in Debian.

### Possible solution

It seems `poetry` itself [declined to implement dynamic versioning as a core feature](https://github.com/python-poetry/poetry/pull/672) in favor of implementing a plugin system.

I haven't done much research, but a quick search online seems to yield a few project that seem maintained:

* https://github.com/mtkennerly/poetry-dynamic-versioning
* https://github.com/tiangolo/poetry-version-plugin

Neither are currently packaged in Debian, but if you choose one of them (or another project) that is properly maintained, I'll be happy to package it myself and maintain in Debian.

### Alternatives

.

### Context

_No response_

### PR DESCRIPTION
**Pull request by s-vitaliy**
Resolves #446

Implemented

- Adopted plugin https://github.com/mtkennerly/poetry-dynamic-versioning from the issue above

The plugin generates version based on git tags:
```
$ poetry build
Building dataclasses-json (0.5.14.post3.dev0+ebe887f)
  - Building sdist
  - Built dataclasses_json-0.5.14.post3.dev0+ebe887f.tar.gz
  - Building wheel
  - Built dataclasses_json-0.5.14.post3.dev0+ebe887f-py3-none-any.whl
```

Where **0.5.14** is the latest git tag, **post3** - number of commits ahead of the tag and **+ebe887f** is git commit SHA.

The **dev0** section added if the lates commit in HEAD is not the release tag.

For instance, if we will create new release tag locally, the plugin will build the following version:
```
$ git tag "v0.5.15"
$ poetry build
Building dataclasses-json (0.5.15)
  - Building sdist
  - Built dataclasses_json-0.5.15.tar.gz
  - Building wheel
  - Built dataclasses_json-0.5.15-py3-none-any.whl
```

- Removed steps that generating version in build pipeline

### CODE REVIEW

**Comment by s-vitaliy** [comment]
@george-zubrienko, take a look. I think we can adopt this plugin in SneaksAndData and use it to build development versions of our python packages as we do with dotnet packages.

**Comment by s-vitaliy** [comment]
@baldurmen, take a look at examples in the PR description, does it solve your issue?

**Comment by baldurmen** [comment]
It does, thank you.

**Review by george-zubrienko — APPROVED** [review]

**Comment by george-zubrienko** [comment]
Huge! :) thanks a lot both @baldurmen and @s-vitaliy

**Pull request merged**
