### PR TITLE
fix: support generic dataclass

### PR DESCRIPTION
**Pull request by PJCampi**
support generic dataclass

### CODE REVIEW

**Review by george-zubrienko — COMMENTED** [review]
@matt035343 wdyt about this? Imo this allows you to squeeze lots of problems in as there are no bounds on T, which means it will always be a string/number/bool, what's the point then?

**Comment by george-zubrienko** [comment]
> It is not a perfect solution at all but the library's coverage improves a little. I can add more tests to better highlight what works and what doesn't.

Please do that - and request review again when ready :)

**Comment by george-zubrienko** [comment]
> After my proposed change, whether the decoding works is down to whether T itself is supported by dataclass_json

Shouldn't we throw in case it is not supported?

**Comment by PJCampi** [comment]
Maybe I should describe my change in more details because the name of the PR (and the ticket I opened) is a bit misleading.

It's not about improving the decoding of type variables in a generic dataclass. That feature currently not supported by the library. The library sets the raw json node to a dataclass field of type T regarldess of its bound, constraints or annotation via `__cls_getitem__`. It never fails:
```
    @dataclass_json
    @dataclass
    class Foo(Generic[T]):
        bar: T

    @dataclass_json
    @dataclass
    class Bar:
        value: int

    assert Foo[Bar].from_json('{"bar": {"value": 1}}') == Foo({"value": 1})  # Bar is not decoded correctly  
```

I am trying to align the behaviour of the library when a generic dataclass is used as type annotation to the behavior I just described.

In the case where a generic dataclass (like `Foo`) is used as part of a type annotation, it is wrapped in an generic wrapper (`_GenericAlias` in python 3.11).

Consider the following example:
```
    @dataclass_json
    @dataclass
    class Baz(Generic[T]):
        foo: Foo[T]
```

On master we silently fail to decode the generic dataclass attribute `foo` and the json node is assigned to the attribute:
```
    assert Baz[int].from_json('{"foo": {"bar": 1}}') == Baz({"bar": 1})
    assert Foo[int].from_json('{"bar": 1}') == Foo(1)
```

After my change we extract the concrete dataclass type from the generic wrapper. The type is now decoded as a dataclass with generic type `T`. The decoding of `foo` becomes consistent with the decoding of an instance of Foo:
```
    assert Baz[int].from_json('{"foo": {"bar": 1}}') == Baz(Foo(1))
    assert Foo[int].from_json('{"bar": 1}') == Foo(1)
```

Throwing an exception instead of silently incorrectly setting a json node to an attribute of complex type would be a good idea but it's orthogonal to my change, and it would be a breaking change to the behaviour of the library. 

I added more test cases now. I did not write any test around type bounds or constraints cause that's not supported by the library anyways.

**Comment by george-zubrienko** [comment]
I am convinced - @matt035343 any additional input or we release?

**Review by george-zubrienko — APPROVED** [review]

**Review by BKAUTO — APPROVED** [review]

**Comment by matt035343** [comment]
> I am convinced - @matt035343 any additional input or we release?

I think it looks good

**Review by matt035343 — APPROVED** [review]

**Comment by george-zubrienko** [comment]
To be released Monday :) fyi @PJCampi - and thanks for contributions and thorough explanations!

**Pull request merged**
