### PR TITLE
Add support for encoding numpy integer and floating point types

### PR DESCRIPTION
**Pull request by pvanheus**
Feel free to ignore if this is too much of an edge case for your module, but I found a need to serialise dataclasses to JSON that had NumPy types (int64 etc) in them. This PR adds support for encoding NumPy types, but only if the numpy module is available.

### CODE REVIEW

**Comment by sebastian-ruiz** [comment]
It would be nice to handle numpy arrays as well. Something like:
```python
elif np_available and _isinstance_safe(o, np.ndarray):
    result = o.tolist()
```

**Comment by pvanheus** [comment]
> It would be nice to handle numpy arrays as well. Something like:
> 
> ```python
> elif np_available and _isinstance_safe(o, np.ndarray):
>     result = o.tolist()
> ```
Thanks, I have belatedly incorporated your suggestion, simplified the code and added a test for encoding to JSON,

**Comment by george-zubrienko** [comment]
I wonder why not use encoder/decoder instead? I've seen people do this with fields being pandas Dataframes

**Comment by matt035343** [comment]
Thanks for your PR. Imo, I believe dataclasses-json should only support native types out of the box while 3rd-party types like numpy can be de/encoded with custom encoders.

**Comment by george-zubrienko** [comment]
I'd say if the author added instead an example for docs with custom encoder/decoder for numpy, that would have helped many people. I'll wait a bit, if no reaction follows, I'll close this one and update docs with examples for both numpy and pandas.

**Comment by matt035343** [comment]
Closing this in favor of #470

**Pull request closed without merging**
